# Derived from https://github.com/cal-icor/base-user-image/blob/main/environment.yml
channels:
  - conda-forge
dependencies:
  # pip and Python
  - python==3.11.*
  - pip==25.2.*
  
  # Git, GitHub
  - gh==2.76.2
  - gh-scoped-creds==4.1
  - git==2.49.0
  - nbdime==4.0.2

  # Jupyter
  - jupyter-resource-usage=1.1.1
  - jupyterhub==5.3.0
  - jupyterlab==4.4.5
  - jupyterlab_widgets==3.0.15
  - ipywidgets==8.1.7
  - jupyter_server==2.16.0
  - jupyterlab-git==0.51.2
  - jupytext==1.17.2
  - notebook==7.4.5
  - nbgitpuller==1.2.2
  - otter-grader=6.1.3
  - jupyterlab-spellchecker==0.8.4
  - jupyter-archive==3.4.0
  
  # nbconvert
  - nbconvert==7.16.6
  - nbconvert[webpdf]
  - nbconvert[qtpdf]
  - nbconvert[qtpng]

  # MATH 108 and STAT C1000 Packages
  - numpy==2.3.2
  - datascience==0.17.6
  - matplotlib==3.10.5
  
  - geopandas==1.1.1
  - openpyxl==3.1.5
  - pandas==2.3.1
  - plotly==6.2.0
  - scikit-learn==1.7.1
  - scipy==1.16.0
  - seaborn==0.13.2
  - statsmodels==0.14.5
  - folium==0.20.0
  - nltk==3.9.1
  - ipympl==0.9.7
  - requests==2.32.4
  - httpx==0.28.1
  - beautifulsoup4==4.13.4
  - html5lib==1.1
  - jupysql==0.11.1

  # vscode
  - code-server==4.102.3
  - jupyter-vscode-proxy==0.6
  - jupyter-server-proxy==4.4.0