name: Build and push container image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files in repo
      uses: actions/checkout@v4

    - name: Build and push image to quay.io
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: "false"
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        DOCKER_REGISTRY: "quay.io"
        LATEST_TAG_OFF: true
        REPO_DIR: /srv/repo
        IMAGE_NAME: "ccsf/jupyterhub"
